[workspace]
authors = ["Kevin Stachelek <kstachel@uci.edu>"]
channels = ["conda-forge"]
name = "snakemake"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.snakemake-dfs]
channels = ["conda-forge", "bioconda"]

[feature.snakemake-dfs.dependencies]
snakemake = "*"
snakefmt = ">=2.0.3,<3"
reportlab = ">=5.0.0,<6"
pillow = ">=12.3.0,<13"
pyyaml = ">=6.0.3,<7"

[feature.snakemake-dfs.tasks]
fmt = "snakefmt Snakefile"

[environments]
snakemake-dfs = { features = ["snakemake-dfs"], no-default-feature = true }
